CREATE TABLE STUDENT (
    STUDENT_ID NUMBER PRIMARY KEY,
    STUDENT_NAME VARCHAR2(30),
    COURSE VARCHAR2(30),
    MARKS NUMBER
);

INSERT ALL
    INTO STUDENT VALUES (101, 'Arun', 'CSE', 85)
    INTO STUDENT VALUES (102, 'Bhavya', 'ECE', 78)
    INTO STUDENT VALUES (103, 'Charan', 'CSE', 90)
    INTO STUDENT VALUES (104, 'Divya', 'IT', 88)
    INTO STUDENT VALUES (105, 'Esha', 'CSE', 76)
    INTO STUDENT VALUES (106, 'Farhan', 'ECE', 82)
SELECT * FROM DUAL;

COMMIT;

CREATE OR REPLACE FUNCTION COUNT_STUDENTS(
    P_COURSE IN VARCHAR2
)
RETURN NUMBER
IS
    V_COUNT NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO V_COUNT
    FROM STUDENT
    WHERE UPPER(COURSE) = UPPER(P_COURSE);

    RETURN V_COUNT;
END;
/

SELECT 'CSE' AS COURSE,
       COUNT_STUDENTS('CSE') AS TOTAL_STUDENTS
FROM DUAL;
