CREATE TABLE EMPLOYEE (
    EMP_ID NUMBER(5) PRIMARY KEY,
    EMP_NAME VARCHAR2(30),
    MONTHLY_SALARY NUMBER(10,2)
);

INSERT INTO EMPLOYEE VALUES (101, 'Arjun', 25000);
INSERT INTO EMPLOYEE VALUES (102, 'Priya', 30000);
INSERT INTO EMPLOYEE VALUES (103, 'Rahul', 35000);
INSERT INTO EMPLOYEE VALUES (104, 'Sneha', 40000);

COMMIT;

CREATE OR REPLACE FUNCTION CALCULATE_ANNUAL_SALARY (
    P_MONTHLY_SALARY IN NUMBER
)
RETURN NUMBER
IS
BEGIN
    RETURN P_MONTHLY_SALARY * 12;
END;
/
