CREATE TABLE STUDENT (
    STUDENT_ID NUMBER PRIMARY KEY,
    STUDENT_NAME VARCHAR2(30),
    MARKS NUMBER
);

INSERT ALL
    INTO STUDENT VALUES (101, 'Arjun', 85)
    INTO STUDENT VALUES (102, 'Arya', 72)
    INTO STUDENT VALUES (103, 'Brinda', 56)
    INTO STUDENT VALUES (104, 'Diya', 45)
    INTO STUDENT VALUES (105, 'Eva', 32)
SELECT * FROM DUAL;

COMMIT;

CREATE OR REPLACE FUNCTION GET_GRADE (
    P_MARKS IN NUMBER
)
RETURN VARCHAR2
IS
    V_GRADE VARCHAR2(20);
BEGIN
    IF P_MARKS >= 75 THEN
        V_GRADE := 'Distinction';

    ELSIF P_MARKS >= 60 AND P_MARKS <= 74 THEN
        V_GRADE := 'First Class';

    ELSIF P_MARKS >= 50 AND P_MARKS <= 59 THEN
        V_GRADE := 'Second Class';

    ELSIF P_MARKS >= 35 AND P_MARKS <= 49 THEN
        V_GRADE := 'Pass';

    ELSE
        V_GRADE := 'Fail';
    END IF;

    RETURN V_GRADE;
END;
/
