CREATE TABLE STUDENT(
NAME VARCHAR2(10) , 
STUDENT_NUMBER NUMBER PRIMARY KEY,
CLASS NUMBER, 
MAJOR VARCHAR2(3) NOT NULL); 

CREATE TABLE COURSE( 
COURSE_NAME VARCHAR2(30), 
COURSE_NUMBER VARCHAR2(15) PRIMARY KEY,  4 CREDIT_HOURS NUMBER NOT NULL, 
DEPARTMENT VARCHAR2(5)); 

CREATE TABLE SECTION( 
SECTION_IDENTIFIER NUMBER(2) PRIMARY KEY,  3 COURSE_NUMBER VARCHAR2(10), 
SEMESTER VARCHAR2(5) NOT NULL, 
YEAR NUMBER, 
INSTRUCTOR VARCHAR2(10)); 

CREATE TABLE GRADE_REPORT( 
STUDENT_NUMBER NUMBER, 
SECTION_IDENTIFIER NUMBER, 
GRADE VARCHAR2(2) NOT NULL, 
PRIMARY KEY(STUDENT_NUMBER,SECTION_IDENTIFIER),
FOREIGN KEY(STUDENT_NUMBER) REFERENCES  STUDENT(STUDENT_NUMBER) ON DELETE CASCADE, 
FOREIGN KEY(SECTION_IDENTIFIER) REFERENCES  SECTION(SECTION_IDENTIFIER) ON DELETE CASCADE); 

desc student; 

 desc course; 

 desc section; 

desc grade_report; 

 INSERT ALL 
INTO STUDENT VALUES ('Smith', 17, 1, 'CS') 
 INTO STUDENT VALUES ('Brown', 8, 2, 'CS') 
SELECT * FROM DUAL; 

 INSERT ALL 
INTO COURSE VALUES ('Intro to Computer Science', 'CS1310', 4, 'CS')  3 INTO COURSE VALUES ('Data Structures', 'CS3320', 4, 'CS')  4 INTO COURSE VALUES ('Discrete Mathematics', 'MATH2410', 3, 'MATH')  5 INTO COURSE VALUES ('Database', 'CS3380', 3, 'CS')  6 SELECT * FROM DUAL; 

 INSERT ALL 
 INTO SECTION VALUES (85, 'MATH2410', 'Fall', 7, 'King')  3 INTO SECTION VALUES (92, 'CS1310', 'Fall', 7, 'Anderson')
 INTO SECTION VALUES (102, 'CS3320', 'Spring', 8, 'Knuth')  5 INTO SECTION VALUES (112, 'MATH2410', 'Fall', 8, 'Chang')  6 INTO SECTION VALUES (119, 'CS1310', 'Fall', 8, 'Anderson')  7 INTO SECTION VALUES (135, 'CS3380', 'Fall', 8, 'Stone')  8 SELECT * FROM DUAL; 

 INSERT ALL 
 INTO GRADE_REPORT VALUES (17, 112, 'B') 
 INTO GRADE_REPORT VALUES (17, 119, 'C') 
 INTO GRADE_REPORT VALUES (8, 85, 'A') 
 INTO GRADE_REPORT VALUES (8, 92, 'A') 
 INTO GRADE_REPORT VALUES (8, 102, 'B') 
 INTO GRADE_REPORT VALUES (8, 135, 'A') 
 SELECT * FROM DUAL; 

select * from student; 

select * from section; 

select * from grade_report; 

 ALTER TABLE STUDENT ADD BRANCH VARCHAR2(5); 

DESC STUDENT; 

UPDATE STUDENT 
 SET BRANCH=MAJOR; 

 SELECT * FROM STUDENT; 

 ALTER TABLE STUDENT DROP COLUMN 
 MAJOR;

  DESC STUDENT; 

ALTER TABLE COURSE RENAME COLUMN COURSE_NAME TO CID; 

 desc course; 

 UPDATE COURSE 
 SET CREDIT_HOURS=4 
 WHERE COURSE_NAME = 'DATABASE'; 

 select * from course; 

ALTER TABLE STUDENT
 MODIFY Branch VARCHAR2(20) NOT NULL; 

 DROP TABLE PUPIL CASCADE CONSTRAINTS; 

DELETE FROM SECTION 
 WHERE Semester = 'Fall'; 

DELETE FROM COURSE WHERE COURSE_NAME
 LIKE 'DATA STRUCTURE'; 

TRUNCATE TABLE PUPIL;

TRUNCATE TABLE COURSE; 

TRUNCATE TABLE SECTION;

 TRUNCATE TABLE GRADE_REPORT; 

DROP TABLE PUPIL; 

DROP TABLE COURSE; 

 DROP TABLE SECTION; 

DROP TABLE GRADE_REPORT; 
