CREATE TABLE EMPLO(  
EMPNO NUMBER(5),  
ENAME VARCHAR2(20),  
SALARY NUMBER(8,2),  
DOJ DATE,  
DEPT VARCHAR2(20));

 INSERT INTO EMPLO VALUES(101,'RAMESH',35000,'15-JAN-2022','CSE'); 

INSERT INTO EMPLO VALUES(102,'SURESH',42000,'20-MAR-2021','ECE');

INSERT INTO EMPLO VALUES(103,'MAHESH',50000,'10-JUL-2020','IT');

 INSERT INTO EMPLO VALUES(104,'ANITHA',28000,'05-FEB-2023','EEE'); 

 INSERT INTO EMPLO VALUES(105,'KAVITHA',45000,'18-AUG 2021','CSE');

  SELECT * FROM EMPLO; 

SELECT EMPNO, TO_CHAR(SALARY,'99,999.99') AS SALARY

SELECT EMPNO, TO_CHAR(DOJ,'DD-MON-YYYY') AS 
JOIN_DATE FROM EMPLO; 

 SELECT TO_NUMBER('5000')+2500 AS TOTAL 
 FROM DUAL; 

 SELECT TO_DATE('25-12-2025','DD-MM-YYYY') 
 FROM DUAL; 

 SELECT ENAME || ' WORKS IN ' || DEPT AS 
 DETAILS FROM EMPLO;

SELECT LPAD(ENAME,12,'*') 
FROM EMPLO;

SELECT RPAD(ENAME,12,'*')
 FROM EMPLO; 

SELECT LTRIM(' ORACLE SQL')
FROM DUAL; 

SELECT RTRIM('ORACLE SQL ')
FROM DUAL;

SELECT
 LOWER(ENAME)FROM
EMPLO; 

SELECT 
UPPER(ENAME)FROM 
EMPLO;

 SELECT INITCAP(ENAME) 
 FROM EMPLO; 

SELECT ENAME,
LENGTH(ENAME)FROM EMPLO;

 SELECT ENAME,
 SUBSTR(ENAME,1,3)FROM EMPLO; 

SELECT ENAME,
INSTR(ENAME,'A')FROM EMPLO; 

SELECT SYSDATE 
FROM DUAL;

SELECT NEXT_DAY(SYSDATE,'MONDAY')
FROM DUAL; 

 SELECT ADD_MONTHS(SYSDATE,6)
 FROM DUAL; 

 SELECT LAST_DAY(SYSDATE)
 FROM DUAL;

SELECT MONTHS_BETWEEN( 
 TO_DATE('01-JAN-2026','DD-MON-YYYY'),
 TO_DATE('01-JAN-2025','DD-MON-YYYY')
 ) AS MONTHS 
 FROM DUAL; 

 SELECT LEAST(20,15,35,40) 
 FROM DUAL; 

 SELECT GREATEST(20,15,35,40)
 FROM DUAL; 

SELECT TRUNC(125.987) 
FROM DUAL;

SELECT ROUND(125.987,2) 
FROM DUAL; 

SELECT TRUNC(SYSDATE,'MONTH') 
FROM DUAL;

SELECT ROUND(SYSDATE) 
FROM DUAL; 

 SELECT TO_CHAR(SYSDATE,'DD/MM/YYYY') AS TODAY
 FROM DUAL; 

 SELECT 
 TO_DATE('15-08-2025','DD-MM-YYYY')
 FROM DUAL;
