SET SERVEROUTPUT ON;

CREATE TABLE EMPLOYEE(
    EID NUMBER PRIMARY KEY,
    ENAME VARCHAR2(20),
    DEPT VARCHAR2(20),
    SALARY NUMBER,
    EXPERIENCE NUMBER
);

INSERT INTO EMPLOYEE VALUES(1,'RAVI','IT',30000,2);
INSERT INTO EMPLOYEE VALUES(2,'ANU','HR',35000,3);
INSERT INTO EMPLOYEE VALUES(3,'RAHUL','IT',40000,4);
INSERT INTO EMPLOYEE VALUES(4,'SITA','SALES',32000,2);

DECLARE
    CURSOR C1(D VARCHAR2) IS
        SELECT * FROM EMPLOYEE
        WHERE DEPT = D
        FOR UPDATE OF SALARY;

    R EMPLOYEE%ROWTYPE;
BEGIN
    OPEN C1('IT');

    LOOP
        FETCH C1 INTO R;
        EXIT WHEN C1%NOTFOUND;

        UPDATE EMPLOYEE
        SET SALARY = SALARY + 3000
        WHERE CURRENT OF C1;

        DBMS_OUTPUT.PUT_LINE(
            R.ENAME || ' - New Salary: ' || (R.SALARY + 3000)
        );
    END LOOP;

    CLOSE C1;
    COMMIT;
END;
/