CREATE TABLE ACCOUNT
(
    ACCOUNT_NO NUMBER(10) PRIMARY KEY,
    CUSTOMER_NAME VARCHAR2(30),
    ACCOUNT_TYPE VARCHAR2(15),
    BALANCE NUMBER(10,2)
);

INSERT INTO ACCOUNT VALUES (1001, 'Rahul', 'SAVINGS', 25000);
INSERT INTO ACCOUNT VALUES (1002, 'Sneha', 'CURRENT', 45000);
INSERT INTO ACCOUNT VALUES (1003, 'Arjun', 'SAVINGS', 32000);
INSERT INTO ACCOUNT VALUES (1004, 'Priya', 'CURRENT', 55000);
INSERT INTO ACCOUNT VALUES (1005, 'Kiran', 'SAVINGS', 28000);

COMMIT;

SET SERVEROUTPUT ON;

DECLARE
    CURSOR C_ACCOUNT(P_TYPE VARCHAR2) IS
        SELECT ACCOUNT_NO, CUSTOMER_NAME, ACCOUNT_TYPE, BALANCE
        FROM ACCOUNT
        WHERE ACCOUNT_TYPE = P_TYPE;
BEGIN
    DBMS_OUTPUT.PUT_LINE('Customers with SAVINGS Account:');
    DBMS_OUTPUT.PUT_LINE('--------------------------------');

    FOR REC IN C_ACCOUNT('SAVINGS') LOOP
        DBMS_OUTPUT.PUT_LINE(
            'Account No: ' || REC.ACCOUNT_NO ||
            ' | Customer: ' || REC.CUSTOMER_NAME ||
            ' | Type: ' || REC.ACCOUNT_TYPE ||
            ' | Balance: ' || REC.BALANCE
        );
    END LOOP;
END;
/