CREATE TABLE BOOK
(
    BOOK_ID NUMBER PRIMARY KEY,
    BOOK_NAME VARCHAR2(30),
    AUTHOR VARCHAR2(30),
    AVAILABLE_COPIES NUMBER
);

INSERT INTO BOOK VALUES (101, 'DBMS', 'Korth', 10);
INSERT INTO BOOK VALUES (102, 'Java', 'Herbert', 15);
INSERT INTO BOOK VALUES (103, 'Python', 'Mark', 20);
INSERT INTO BOOK VALUES (104, 'Oracle', 'Scott', 12);

COMMIT;

SET SERVEROUTPUT ON;

DECLARE
    CURSOR C_BOOK IS
        SELECT BOOK_ID, AVAILABLE_COPIES
        FROM BOOK
        FOR UPDATE;
BEGIN
    FOR REC IN C_BOOK LOOP
        UPDATE BOOK
        SET AVAILABLE_COPIES = AVAILABLE_COPIES + 5
        WHERE CURRENT OF C_BOOK;
    END LOOP;

    COMMIT;

    DBMS_OUTPUT.PUT_LINE('Book copies updated successfully.');
END;
/