CREATE TABLE EMPLOYEE
(
    EMPLOYEE_ID NUMBER PRIMARY KEY,
    EMPLOYEE_NAME VARCHAR2(30),
    DEPARTMENT VARCHAR2(20),
    SALARY NUMBER(10,2)
);

INSERT INTO EMPLOYEE VALUES (101, 'Rahul', 'CSE', 30000);
INSERT INTO EMPLOYEE VALUES (102, 'Sneha', 'ECE', 35000);
INSERT INTO EMPLOYEE VALUES (103, 'Arjun', 'IT', 40000);
INSERT INTO EMPLOYEE VALUES (104, 'Priya', 'HR', 32000);

COMMIT;

SET SERVEROUTPUT ON;

DECLARE
    CURSOR C_EMP IS
        SELECT EMPLOYEE_ID, SALARY
        FROM EMPLOYEE
        FOR UPDATE;
BEGIN
    FOR REC IN C_EMP LOOP
        UPDATE EMPLOYEE
        SET SALARY = SALARY * 1.10
        WHERE CURRENT OF C_EMP;
    END LOOP;

    COMMIT;

    DBMS_OUTPUT.PUT_LINE('Salary updated successfully.');
END;
/