CREATE TABLE PRODUCT
(
    PRODUCT_ID NUMBER PRIMARY KEY,
    PRODUCT_NAME VARCHAR2(30),
    PRICE NUMBER(10,2),
    QUANTITY NUMBER
);

INSERT INTO PRODUCT VALUES (101, 'Laptop', 50000, 10);
INSERT INTO PRODUCT VALUES (102, 'Keyboard', 2000, 20);
INSERT INTO PRODUCT VALUES (103, 'Mouse', 1000, 30);
INSERT INTO PRODUCT VALUES (104, 'Monitor', 15000, 15);

COMMIT;

SET SERVEROUTPUT ON;

DECLARE
    CURSOR C_PRODUCT IS
        SELECT PRODUCT_ID, PRICE
        FROM PRODUCT
        FOR UPDATE;
BEGIN
    FOR REC IN C_PRODUCT LOOP
        UPDATE PRODUCT
        SET PRICE = PRICE * 1.05
        WHERE CURRENT OF C_PRODUCT;
    END LOOP;

    COMMIT;

    DBMS_OUTPUT.PUT_LINE('Product prices updated successfully.');
END;
/