SET SERVEROUTPUT ON;
CREATE TABLE EMPLOYEE (
    EMP_ID NUMBER PRIMARY KEY,
    EMP_NAME VARCHAR2(30),
    SALARY NUMBER(10,2)
);
INSERT INTO EMPLOYEE VALUES (101, 'Ravi', 30000);
INSERT INTO EMPLOYEE VALUES (102, 'Sita', 35000);
INSERT INTO EMPLOYEE VALUES (103, 'Arun', 40000);
COMMIT;
CREATE TABLE DELETE_LOG (
    LOG_ID NUMBER,
    MESSAGE VARCHAR2(100),
    DELETE_TIME DATE
);
CREATE OR REPLACE TRIGGER AFTER_EMP_DELETE
AFTER DELETE ON EMPLOYEE
BEGIN
    INSERT INTO DELETE_LOG
    VALUES (
        1,
        'DELETE operation completed on EMPLOYEE table',
        SYSDATE
    );
    DBMS_OUTPUT.PUT_LINE(
        'DELETE operation completed successfully.'
    );
END;
/
DELETE FROM EMPLOYEE
WHERE EMP_ID IN (101, 102);
COMMIT;
SELECT * FROM EMPLOYEE;
SELECT * FROM DELETE_LOG;