CREATE TABLE STUDENT_TRIGGER (
    STUDENT_ID NUMBER(5),
    STUDENT_NAME VARCHAR2(30),
    MARKS NUMBER(3)
);
CREATE OR REPLACE TRIGGER BEFORE_STUDENT_INSERT
BEFORE INSERT ON STUDENT_TRIGGER
FOR EACH ROW
BEGIN
    IF :NEW.MARKS < 0 OR :NEW.MARKS > 100 THEN
        RAISE_APPLICATION_ERROR(
            -20001,
            'Marks must be between 0 and 100'
        );
    END IF;
END;
/
INSERT INTO STUDENT_TRIGGER
VALUES (101, 'Ravi', 85);
INSERT INTO STUDENT_TRIGGER
VALUES (102, 'Sita', 120);
SELECT * FROM STUDENT_TRIGGER;