SET SERVEROUTPUT ON;
CREATE TABLE EMPLOYEE (
    EID NUMBER PRIMARY KEY,
    ENAME VARCHAR2(30),
    SALARY NUMBER(10,2)
);
INSERT INTO EMPLOYEE VALUES (101, 'Ravi', 25000);
INSERT INTO EMPLOYEE VALUES (102, 'Sita', 30000);
INSERT INTO EMPLOYEE VALUES (103, 'Arun', 20000);
COMMIT;
CREATE OR REPLACE TRIGGER CHECK_SALARY_UPDATE
BEFORE UPDATE OF SALARY ON EMPLOYEE
FOR EACH ROW
BEGIN
    IF :NEW.SALARY < :OLD.SALARY THEN
        RAISE_APPLICATION_ERROR(
            -20001,
            'Salary cannot be decreased'
        );
    END IF;
    IF :NEW.SALARY < 5000 THEN
        RAISE_APPLICATION_ERROR(
            -20002,
            'Salary must be at least 5000'
        );
    END IF;
END;
/
UPDATE EMPLOYEE
SET SALARY = 28000
WHERE EID = 101;
COMMIT;
UPDATE EMPLOYEE
SET SALARY = 20000
WHERE EID = 101;
UPDATE EMPLOYEE
SET SALARY = 3000
WHERE EID = 102;
SELECT * FROM EMPLOYEE;