CREATE TABLE EMPLOYEE (
    EID NUMBER(5) PRIMARY KEY,
    ENAME VARCHAR2(30),
    SALARY NUMBER(10,2)
);
INSERT INTO EMPLOYEE VALUES (101, 'Ravi', 25000);
INSERT INTO EMPLOYEE VALUES (102, 'Sita', 30000);
INSERT INTO EMPLOYEE VALUES (103, 'Kiran', 28000);
COMMIT;
SELECT * FROM EMPLOYEE;
CREATE OR REPLACE VIEW EMP_VIEW AS
SELECT EID, ENAME, SALARY
FROM EMPLOYEE;
CREATE OR REPLACE TRIGGER TRG_EMP_UPDATE
INSTEAD OF UPDATE ON EMP_VIEW
FOR EACH ROW
BEGIN
    UPDATE EMPLOYEE
    SET ENAME = :NEW.ENAME,
        SALARY = :NEW.SALARY
    WHERE EID = :OLD.EID;
END;
/
UPDATE EMP_VIEW
SET ENAME = 'Ravi Kumar',
    SALARY = 35000
WHERE EID = 101;
COMMIT;
SELECT * FROM EMPLOYEE;