SET SERVEROUTPUT ON;
CREATE TABLE EMPLOYEE (
    EMP_ID NUMBER PRIMARY KEY,
    EMP_NAME VARCHAR2(30),
    SALARY NUMBER(10,2)
);
CREATE TABLE EMPLOYEE_AUDIT (
    EMP_ID NUMBER,
    EMP_NAME VARCHAR2(30),
    SALARY NUMBER(10,2),
    ACTION_TYPE VARCHAR2(20),
    ACTION_DATE DATE
);
CREATE OR REPLACE TRIGGER EMPLOYEE_AFTER_INSERT
AFTER INSERT ON EMPLOYEE
FOR EACH ROW
BEGIN
    INSERT INTO EMPLOYEE_AUDIT (
        EMP_ID,
        EMP_NAME,
        SALARY,
        ACTION_TYPE,
        ACTION_DATE
    )
    VALUES (
        :NEW.EMP_ID,
        :NEW.EMP_NAME,
        :NEW.SALARY,
        'INSERT',
        SYSDATE
    );
END;
/
INSERT INTO EMPLOYEE
VALUES (101, 'RAVI', 35000);
SELECT * FROM EMPLOYEE;
SELECT * FROM EMPLOYEE_AUDIT;