CREATE TABLE STU ( 
 2 ROLLNO NUMBER(5), 
 3 NAME VARCHAR2(30), 
 4 MARKS NUMBER(3) 
 5 ); 

INSERT INTO STU VALUES (101, 'AKHIL', 85); 
INSERT INTO STU VALUES (102, 'BHAVANA', 72); 
INSERT INTO STU VALUES (103, 'CHARAN', 65);
INSERT INTO STU VALUES (104, 'DIVYA', 58);
INSERT INTO STU VALUES (105, 'ESWAR', 90); 
COMMIT;

SET SERVEROUTPUT ON; 
DECLARE 
CURSOR C1 IS 
SELECT ROLLNO, NAME, MARKS 
FROM STU 
WHERE MARKS >= 60; 
VROLL STU.ROLLNO%TYPE; 
VNAME STU.NAME%TYPE; 
VMARKS STU.MARKS%TYPE; 
NO_FIRST_CLASS EXCEPTION; 
CNT NUMBER := 0; 
BEGIN 
OPEN C1; 
LOOP 
FETCH C1 INTO VROLL, VNAME, VMARKS; 15 EXIT WHEN C1%NOTFOUND; 
DBMS_OUTPUT.PUT_LINE ('ROLL NO : ' || VROLL); 17 DBMS_OUTPUT.PUT_LINE ('NAME : ' || VNAME); 18 DBMS_OUTPUT.PUT_LINE('MARKS : ' || VMARKS); 19 DBMS_OUTPUT.PUT_LINE ('------------------------'); 20 CNT := CNT + 1; 
END LOOP; 
CLOSE C1; 
IF CNT = 0 THEN 
RAISE NO_FIRST_CLASS; 
END IF; 
EXCEPTION
WHEN NO_FIRST_CLASS THEN 
DBMS_OUTPUT.PUT_LINE ('NO STUDENT SECURED FIRST  CLASS.'); 
WHEN OTHERS THEN 
DBMS_OUTPUT.PUT_LINE('ERROR: ' || SQLERRM); 31 END; 
/ 
