CREATE TABLE STU ( 
ROLLNO NUMBER(5), 
NAME VARCHAR2(30), 
MARKS NUMBER(3) 
); 

INSERT INTO STU VALUES (101, 'AKHIL', 85); 
SAVEPOINT SP1; 
INSERT INTO STU VALUES (102, 'BHAVANA', 78); 
INSERT INTO STU VALUES (103, 'CHARAN', 90); 
ROLLBACK TO SP1; 
COMMIT;

SET SERVEROUTPUT ON; 
BEGIN 
INSERT INTO STU VALUES (101,'AKHIL',85);  3 SAVEPOINT SP1; 
INSERT INTO STU VALUES (102,'BHAVANA',78);  5 ROLLBACK TO SP1; 
COMMIT; 
DBMS_OUTPUT.PUT_LINE('TRANSACTION COMPLETED  SUCCESSFULLY.'); 
EXCEPTION 
WHEN OTHERS THEN 
ROLLBACK; 
DBMS_OUTPUT.PUT_LINE(SQLERRM); 
END; 
/ 

SELECT * FROM STU;