CREATE TABLE DEPARTMENT ( 
 DEPTNO NUMBER(3) PRIMARY KEY, 
 DNAME VARCHAR2(20), 
 LOCATION VARCHAR2(20) 
 ); 

 CREATE TABLE emp( 
 EMPNO NUMBER(5) PRIMARY KEY, 
 ENAME VARCHAR2(20), 
 SALARY NUMBER(8), 
 DEPTNO NUMBER(3), 
 CONSTRAINT FK_DEPT 
 FOREIGN KEY(DEPTNO) 
 REFERENCES DEPARTMENT(DEPTNO) 
 ); 

INSERT INTO DEPARTMENT VALUES (10,'CSE','Block-A'); 
 INSERT INTO DEPARTMENT VALUES (20,'ECE','Block-B'); 
INSERT INTO DEPARTMENT VALUES (30,'EEE','Block-C'); 
 INSERT INTO DEPARTMENT VALUES (40,'MECH','Block-D'); 
 INSERT INTO EMP VALUES (101,'Akhil',50000,10); 
 INSERT INTO EMP VALUES (102,'Bhavana',45000,20); 
  INSERT INTO EMP VALUES (103,'Charan',55000,10); 
  INSERT INTO EMP VALUES (104,'Divya',48000,30); 
   INSERT INTO EMP VALUES (105,'Eswar',60000,NULL); 

DESC EMP;

DESC DEPARTMENT; 

 SELECT E. EMPNO, 
 E.ENAME, 
 D.DNAME 
 FROM EMP E, DEPARTMENT D 
 WHERE E.DEPTNO = D.DEPTNO;

  SELECT E.EMPNO, 
 E.ENAME, 
 D.DNAME, 
 D.LOCATION 
 FROM EMPLOYEE E 
 INNER JOIN DEPARTMENT D 
 ON E.DEPTNO = D.DEPTNO; 

 SELECT * from department;

 select * from emp; 

SELECT E.EMPNO, E.ENAME,
 D.DNAME FROM EMP E 
 INNER JOIN DEPARTMENT D 
 ON E.DEPTNO = D.DEPTNO; 

 SELECT E.EMPNO, E.ENAME, 
 D.DNAME FROM EMP E 
 RIGHT OUTER JOIN DEPARTMENT D  
 ON E.DEPTNO = D.DEPTNO; 

 SELECT E.EMPNO, E.ENAME,
  D.DNAME FROM EMP E 
 FULL OUTER JOIN DEPARTMENT D
ON E.DEPTNO = D.DEPTNO; 
































